---
title: "Increased Goal Scoring in the NHL: An Attempt To Expand Popularity"
subtitle: "An Analysis of the Increase in Goal Scoring From 2011 to 2023"
author: 
  - Jason Ngo
thanks: "Code and data are available at: https://github.com/thejasonminh/nhlpoints"
date: "`r Sys.time()`"
date-format: "D MMMM YYYY"
format: 
  pdf:
    documentclass: article
    geometry: margin = 1in
    abstract: "Of the four major sports in the USA, hockey is the least popular. In an effort to grow popularity, the NHL (National Hockey League) strove to increase goal scoring. Using data from the NHL, the paper will analyze average leaguewide goal scoring per game from the 2011-2012 to 2022-2023 seaons. A linear regression model will also be created to predict goal scoring averages in the upcoming seasons. Results show that the NHL was succesful as the average goals per game increased over a 10 year period. These findings suggest that increased player talent, more penalties and rule changes have resulted in more goals."
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
```


# Introduction

rework this in the context of goal scoring

Hockey, Baseball, Football, and Basketball have become so popular in the United States, they've become branded as the "Four Major Sports of the USA." The top leagues that operate in each sport: The NHL, MLB, NFL and NBA are centralized in the USA. Many of the top players that have played, or currently play, in these leagues are American, and their popularity only serves to inspire more youth to follow in their footsteps. There are no other sports that can threaten the stranglehold that these four sports have on the USA.

However, Hockey has begun to fall behind the other three. Viewership, revenue and general popularity all pale in comparison to the other three leagues. As a result; player salaries are lower in comparison to other sports and there is less youth talent in the pipelines. Two of the biggest factors for this decline are: High prices and low scoring. Due to the high upfront price of equipment and the amount of equipment required, many kids elect not to choose hockey as their sport and instead elect for cheaper options such as basketball, which only requires proper footwear. Low scoring was a result of goalies having too much freedom, and teams creating bulletproof defensive tactics that involved clogging the middle of the ice and using their goalie to stifle momentum.

As a response to the declining popularity, the NHL decided to implement rule changes with the primary motive of increasing goal scoring in mind. By increasing goal scoring, games would be more exciting which in turn, would lead to increased viewership. This paper will analyze the effectiveness of these changes by drawing data from the NHL to analyze average leaguewide goal scoring per game from the 2011-2012 season to the current (2022-2023) season. In addition, the paper will draw on a linear regression model to predict average goal scoring for future seasons. The findings show that the rule changes, in addition to increased player talent, greatly increased average goals scored per game with every season. The NHL has successfully made the game more exciting by encouraging more goals, which drew more eyes to the game, but how can they keep those eyes glued to the game?

In section 1 of the paper, the source of the data is discussed. Strengths and weaknesses, methods of collection and terminologies will be explored. Section 2 of the paper will introduce a linear model, its justifications, and how it was constructed. Section 3 will discuss the results, touching on the trends and events that occurred over a 10-season period. Section 4 of the paper will touch on the factors that contributed to increased goal scoring. Weaknesses and next steps will be discussed in the final section of the paper.


# Data {#sec-data}
talk about league dataset, forwards and dmen dataset
talk about merging the nhl shooting pct into the league dataset
talk about why i didnt choose to use nhl.com for league dataset(annoying to work with 12 datasets)
talk about why i chose the columns i chose
talk about why i chose the ppg values for forwards and dmen
relationship between save pct, gaa, goals/game and shooting pct

data is collected real time every game, with internal models used to calculate the special stats
[@citeR]

# Model

The goal of our modelling strategy is twofold. Firstly,...

Here we briefly describe the Bayesian analysis model used to investigate... Background details and diagnostics are included in [Appendix -@sec-model-details].

## Model set-up

Define $y_i$ as the number of seconds that the plane remained aloft. Then $\beta_1$ is the wing width and $\gamma_i$ is the wing length, both measured in millimeters. $\beta_1$ is teamwide shooting percentage, $\beta_2$ is teamwide powerplay percentage, $\beta_3$ is penalties drawn per 60.

\begin{align} 
y_i|\mu_i, \sigma &\sim \mbox{Normal}(\mu_i, \sigma) \\
\mu_i &= \alpha + \beta_i + \gamma_i\\
\alpha &\sim \mbox{Normal}(0, 2.5) \\
\beta &\sim \mbox{Normal}(0, 2.5) \\
\gamma &\sim \mbox{Normal}(0, 2.5) \\
\sigma &\sim \mbox{Exponential}(1)
\end{align}

We run the model in R [@citeR] using the `rstanarm` package of @rstanarm. We use the default priors from `rstanarm`.

### Model justification

We expect a positive relationship between the size of the wings and time spent aloft. In particular...

We can use maths by including latex between dollar signs, for instance $\theta$.


# Results

12 season trends in league data
increase in good forwards and defensemen

# Discussion

goal scoring did increase, why?
player talent increased -> correlates to better powerplays
rule changes = less powerplays, could effect even strength scoring
goalie equipment changing

weaknesses = i did not go into an extreme in-depth level of the players themselves. there is a whole world of advance stats that could be used to analyze the increase of player talent.

next steps = analyze viewership data to see the effect goal scoring has had on it. if we want to focus more on growing game, analysis on rivalries, game streaming and media narratives should be done.

\newpage

# References


